[package]
name = "prayer_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.133"
serde = { version = "1.0", features = ["derive"]}
reqwest = {version = "0.12.9", features = ["blocking", "json"]}
chrono = "0.4.39"
